"use client";
import { useCurrentAccount, useDAppKit } from "@mysten/dapp-kit-react";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
type Message = { id: number; address: string; username: string; message: string; createdAt: number };
const short = (value: string) => `${value.slice(0, 6)}…${value.slice(-4)}`;
export function ChatDrawer() {
  const account = useCurrentAccount(); const kit = useDAppKit(); const bottom = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const [draft, setDraft] = useState(""); const [error, setError] = useState(""); const [posting, setPosting] = useState(false);
  useEffect(() => {
    document.body.classList.toggle("chat-drawer-open", open);
    return () => document.body.classList.remove("chat-drawer-open");
  }, [open]);
  const refresh = useCallback(async () => { try { const response = await fetch("/api/chat", { cache: "no-store" }); const data = await response.json() as { messages?: Message[]; error?: string }; if (!response.ok) throw new Error(data.error); setMessages(data.messages ?? []); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Chat unavailable"); } }, []);
  useEffect(() => { if (!open) return; void refresh(); const timer = window.setInterval(() => void refresh(), 12_000); return () => window.clearInterval(timer); }, [open, refresh]);
  useEffect(() => { if (open) requestAnimationFrame(() => bottom.current?.scrollIntoView()); }, [messages, open]);
  async function post(event: FormEvent) { event.preventDefault(); const message = draft.trim(); if (!account || !message || posting) return; setPosting(true); setError(""); try { const address = account.address.toLowerCase(); const timestamp = Date.now(); const approval = `SLVRBLOX community chat\nWallet: ${address}\nTimestamp: ${timestamp}\nMessage: ${message}`; const signed = await kit.signPersonalMessage({ message: new TextEncoder().encode(approval) }); const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ address, message, timestamp, bytes: signed.bytes, signature: signed.signature }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error); setDraft(""); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Message was not posted"); } finally { setPosting(false); } }
  return <><button className={`chat-drawer-toggle${open ? " open" : ""}`} aria-label={open ? "Close community chat" : "Open community chat"} aria-expanded={open} onClick={() => setOpen((value) => !value)}>{open ? "×" : <><span>●</span><i>{messages.length || ""}</i></>}</button><aside className={`chat-drawer${open ? " open" : ""}`} aria-hidden={!open}><header><div><p>SLVRBLOX COMMUNITY</p><strong>Miner Chat</strong></div><Link href="/chat">Full view ↗</Link><button aria-label="Close chat" onClick={() => setOpen(false)}>×</button></header><div className="chat-drawer-feed">{messages.length ? messages.map((item) => <article className={item.address === account?.address.toLowerCase() ? "mine" : ""} key={item.id}><div><strong>{item.username || short(item.address)}</strong><time>{new Date(item.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time></div><p>{item.message}</p></article>) : <p className="chat-drawer-empty">No messages yet. Say hello to the miners.</p>}<div ref={bottom} /></div>{account ? <form onSubmit={post}><textarea rows={2} maxLength={500} value={draft} placeholder="Type your message…" onChange={(event) => setDraft(event.target.value)} /><div><small>{draft.length}/500</small><button disabled={!draft.trim() || posting}>{posting ? "Approving…" : "Sign & send"}</button></div></form> : <div className="chat-drawer-locked"><strong>Connect wallet to chat</strong><span>Messages are public and wallet verified.</span></div>}{error && <p className="chat-drawer-error">{error}</p>}</aside></>;
}
