import type { Metadata } from "next";
import { ProtocolPage } from "../protocol-page";

export const metadata: Metadata = { title: "Roadmap | SLVRBLOX", description: "Current SLVRBLOX development roadmap." };

export default function RoadmapPage() {
  return <ProtocolPage eyebrow="DEVELOPMENT PLAN" title="Roadmap" intro="SLVRBLOX will advance by verified milestones rather than promised dates. Proposed features remain subject to Testnet results, independent review, legal review, and sustainable player activity." sections={[
    { title: "1. Testnet and audit — active", items: ["Complete independent Move security review, remediate findings, and freeze the Mainnet release candidate.", "Continue testing gameplay, autoplay, settlement, DSLVR rewards, refinery claims, allocation limits, and keeper recovery.", "Rehearse multisig custody, monitoring, incident response, and every Mainnet deployment transaction."] },
    { title: "2. Mainnet foundation", items: ["Publish only the reviewed contracts and verify every live object, capability, destination address, and integration before opening play.", "Launch conservatively with protocol-owned liquidity and separate multisig-controlled Treasury, Operations, Staking, Team, and Liquidity custody.", "Keep issuance demand-based: allocation caps authorize future releases, but tokens do not need to be minted before they are required.", "Direct each played round according to the published 90% player / 5% Treasury / 3% Operations / 2% Buyback-and-Burn Reserve model; keeper reimbursement remains separate."] },
    { title: "3. Staking and DSLVR utility", items: ["Activate simple single-asset DSLVR staking after its seven-day minimum lock and reward accounting pass Testnet and audit review.", "Prototype optional Deployment Boosts paid in DSLVR that increase DSLVR mining rewards only—not SUI winnings, winning odds, or Motherlode odds.", "Evaluate a Miner Profile and transferable Miner or Tool NFTs with useful, bounded perks such as autoplay capacity and a capped Motherlode payout benefit.", "Model DSLVR payment flows for boosts, NFTs, and upgrades, with transparent portions assigned to burn and self-funded reward reserves."] },
    { title: "4. Sustainable protocol growth", items: ["Execute buybacks manually through approved multisig custody only when revenue, liquidity, and market conditions justify them.", "Explore sponsored SUI gas as a separate protected service where users may pay a quoted DSLVR amount; DSLVR does not replace SUI as network gas.", "Grow integrations, listings, keeper participation, and community features only after Mainnet reliability and real usage are established."] },
    { title: "5. Strategic reserves — research", items: ["Consider building a transparent, unleveraged protocol reserve from a portion of realized Treasury profits, separate from liquidity, operations, staking, and prize funds.", "Potential reserve assets include SUI, USDC, tokenized gold such as XAUm, and bridged ETH, subject to custody, liquidity, bridge, and legal review.", "Research a separately funded rare ETH Treasure Vault for active settled rounds. Probability, payout limits, and any NFT benefit must be independently reviewed before implementation.", "Reserve assets would strengthen Treasury resilience; they would not make DSLVR redeemable for those assets or guarantee a market price."] },
  ]} />;
}
